#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// Header substitutes for on-host testing.
// Defines things that are generated by STM32 headers
// https://github.com/CharlesDias/stm32_gtest_c_code/tree/main/tests/header-overrides
#include "main.h"
#include "trice.h"

#ifdef __cplusplus
}
#endif

